[bars.example]
position = "top"
height = 36
transparent = true
bg = "#0000"
default_bg = "#0000"
default_fg = "#ccc"
default_font = "FiraCode Nerd Font 10"
margin_left = 10
margin_internal = 10
margin_right = 10
panels_left = ["xwindow"]
panels_center = ["clock"]
panels_right = ["pulseaudio","first_separator","network","separator","battery"]
ipc = true

[panels.xwindow]
type = "xwindow"

[panels.pulseaudio]
type = "pulseaudio"
ramp = "pa"
ramp_muted = "pa_muted"

[panels.network]
type = "network"
if_name = "wlan0"
# if_name = "eth0"
format_connected = "<span foreground='#0ff'>%ifname%</span> %essid% %local_ip%"
format_disconnected = "<span foreground='#0ff'>%ifname%</span> <span foreground='#888'>disconnected</span>"

[panels.mpd]
type = "mpd"
progress_bar = true
max_width = 30
strategy = "scroll"
scroll_interval = 1000

[panels.battery]
type = "battery"

[panels.clock]
type = "clock"
precision = "seconds"
formats = ["<span foreground='#0ff'>%Y-%m-%d %T</span>", "<span foreground='#f00'>%Y-%m-%d %T</span>"]
click-left = "cycle"

[panels.separator]
type = "separator"
format = "<span font='FiraCode Nerd Font Mono 13' foreground='#666'>  //  </span>"
dependence = "right"

[panels.first_separator]
type = "separator"
format = "<span font='FiraCode Nerd Font Mono 13' foreground='#666'>  //  </span>"
dependence = "both"

[ramps.pa]
0 = "<span font_size='25pt' rise='-7.5pt'>󰕿</span> "
1 = "<span font_size='25pt' rise='-7.5pt'>󰖀</span> "
2 = "<span font_size='25pt' rise='-7.5pt'>󰕾</span> "

[ramps.pa_muted]
0 = "<span font_size='25pt' rise='-7.5pt'>󰸈</span> "
1 = "<span font_size='25pt' rise='-7.5pt'>󰖁</span> "
