mod battery;
mod clock;
mod custom;
mod fanotify;
mod inotify;
mod network;
mod pulseaudio;
mod separator;
mod xwindow;
mod xworkspaces;

pub use battery::*;
pub use clock::*;
pub use custom::*;
pub use fanotify::*;
pub use inotify::*;
pub use network::*;
pub use pulseaudio::*;
pub use separator::*;
pub use xwindow::*;
pub use xworkspaces::*;
