mod battery;
mod clock;
mod custom;
mod fanotify;
mod inotify;
mod mpd;
mod network;
mod pulseaudio;
mod separator;
mod xwindow;
mod xworkspaces;

pub use battery::Battery;
pub use clock::{precision, Clock};
pub use custom::Custom;
pub use fanotify::Fanotify;
pub use inotify::Inotify;
pub use mpd::Mpd;
pub use network::Network;
pub use pulseaudio::Pulseaudio;
pub use separator::Separator;
pub use xwindow::XWindow;
pub use xworkspaces::XWorkspaces;
